### PR TITLE
Proposed documentation structure

### PR DESCRIPTION
**Pull request by docsteveharris**
Please find a proposed table of contents with (largely) empty placeholder files).
I would hope that it's good enough that people could review and work out where they might write their documentation, and call out out when that is not obvious.

The general principle is that there is

- a quickstart landing area
- a section per persona (I will create a separate issue to discuss consistent naming for them)
- an anatomy area to hold detailed notes on components of the infrastructure
- an FAQ to drop off short mixed notes
- a vignettes section to hold short exemplar notebooks

### CODE REVIEW

**Review by nels — DISMISSED** [review]
Looks good @docsteveharris :+1: 

Only suggestion would be to use 1st person for the personas, e.g.
> As a steward _I_ am responsible for X, Y, Z

Just stylistic but is a more common form for persona writing in software dev
Feel free to ignore

**Comment by docsteveharris** [comment]
> Looks good @docsteveharris 👍
> 
> Only suggestion would be to use 1st person for the personas, e.g.
> 
> > As a steward _I_ am responsible for X, Y, Z
> 
> Just stylistic but is a more common form for persona writing in software dev Feel free to ignore

Edits made in #e5a75dd

**Comment by docsteveharris** [comment]
@anastasiakuzn we ok to merge?

**Review by anastasiakuzn — APPROVED** [review]
Approving this PR, as per discussion.

**Comment by anastasiakuzn** [comment]
@docsteveharris , okay to merge from my perspective. @damoodamoo , okay with you as well ?

**Pull request merged**
